default: &default
 adapter: postgresql
 encoding: unicode
 pool: 10
 username: postgres
 password: root
 host: localhost

development:
 <<: *default
 database: agreements_api_dev

test:
 <<: *default
 database: agreements_api_test
